name: OriginsReforged-Fantasy
version: ${version}
main: ru.turbovadim.addon.fantasy.FantasyAddon
description: Fantasy origins addon for Origins-Reforged
api-version: '1.20'
author: turbovadim
depend:
  - Origins-Reforged
