name: OriginsReforged-Magic
version: ${version}
main: ru.turbovadim.addon.magic.MagicAddon
description: Magic origins addon for Origins-Reforged (ported from Origins-Magic by StarshooterCity)
api-version: '1.20'
author: turbovadim
depend:
  - Origins-Reforged
